# Generated by Django 6.1.1 on 2026-10-06 16:25

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('active_key', models.CharField(blank=True, editable=False, max_length=49, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to=settings.AUTH_USER_MODEL)),
                ('receiver_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_exchanges', to='skills.skill')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_sent', to=settings.AUTH_USER_MODEL)),
                ('sender_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_exchanges', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exchanges.exchangerequest')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'reviewer'), name='one_review_per_participant')],
            },
        ),
    ]
