# Farhan's part
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'development-only-skillswap-change-before-deployment')
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'
ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]').split(',') if host.strip()]
if not DEBUG and SECRET_KEY == 'development-only-skillswap-change-before-deployment':
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY before disabling DEBUG.')

# Application definition

INSTALLED_APPS = [
    'farhan.config.apps.MongoAdminConfig',
    'farhan.config.apps.MongoAuthConfig',
    'farhan.config.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mongodb_backend',
    'farhan.accounts.apps.AccountsConfig',
    'ankon.skills.apps.SkillsConfig',
    'pranay.exchanges.apps.ExchangesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'farhan.accounts.middleware.PreserveLoginBackendMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farhan.config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farhan.config.wsgi.application'
ASGI_APPLICATION = 'farhan.config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

MONGODB_URI = os.getenv('MONGODB_URI', '').strip()
if MONGODB_URI == 'your_mongodb_atlas_connection_string_here':
    MONGODB_URI = ''
MONGODB_CONFIGURED = MONGODB_URI.startswith(('mongodb://', 'mongodb+srv://'))
# Offline checks and migration generation do not require a live connection.
OFFLINE_COMMANDS = {'check', 'makemigrations', 'test', 'collectstatic', 'findstatic', 'help'}
if not MONGODB_CONFIGURED and not (len(sys.argv) > 1 and sys.argv[1] in OFFLINE_COMMANDS):
    raise ImproperlyConfigured(
        'MongoDB is not configured. Copy .env.example to .env and set MONGODB_URI '
        'to your Atlas URI, then run python manage.py migrate. '
        'python manage.py check works without credentials.'
    )
DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'HOST': MONGODB_URI or None,
        'NAME': os.getenv('MONGODB_NAME', 'skillswap'),
        'OPTIONS': {'serverSelectionTimeoutMS': 5000},
    }
}
MIGRATION_MODULES = {
    'admin': 'farhan.mongo_migrations.admin',
    'auth': 'farhan.mongo_migrations.auth',
    'contenttypes': 'farhan.mongo_migrations.contenttypes',
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Real application views supply data; demo mode stays disabled.
SKILLSWAP_DEMO_MODE = False
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'staticfiles'
AUTHENTICATION_BACKENDS = ['farhan.accounts.backends.UsernameOrEmailBackend']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

DATABASE_ROUTERS = ['farhan.config.routers.OfflineMigrationRouter']
